### ISSUE TITLE
如何禁用360极速浏览器等浏览器自带的小窗口播放功能

### ISSUE THREAD

**Issue by GoldenZqqq** [xdlumia/vue3-video-play#120]
![image](https://github.com/xdlumia/vue3-video-play/assets/76801182/3602e31f-9e19-4736-a6ba-e6cb9e1b70ec)
需求：希望用户不能下载播放的视频资源，如果使用360极速浏览器等 点击如图所示小窗口播放按钮，就能正常下载视频资源
如何禁用360极速浏览器等浏览器自带的小窗口播放功能

**Comment by LXG19961206** [comment]
只能提示用户别用这种野鸡浏览器
