### ISSUE TITLE
是否可以控制能否拖动进度条

### ISSUE THREAD

**Issue by zjsxfly** [xdlumia/vue3-video-play#2]
有一个培训需求，需要对课程视频不能拖动进度

**Comment by xdlumia** [comment]
暂时不支持.不过可以 把class` d-control-progress` 设置为display:none, 隐藏进度条.这周末我会添加此类功能

**Comment by xdlumia** [comment]
> 有一个培训需求，需要对课程视频不能拖动进度

刚刚发布了 `vue3-video-play@1.2.2`版本 可以`speed`来开启或者关闭进度条啦，如果也想关闭倍速播放，在`speedRate`里配置成`[1.0]`即可
