### ISSUE TITLE
想请教一下切换清晰度时报错？ Hls is not defined

### ISSUE THREAD

**Issue by Runle1** [xdlumia/vue3-video-play#33]
切换清晰度时报错？runtime-core.esm-bundler.js?5c40:6769 Uncaught ReferenceError: Hls is not defined
![1637567629(1)](https://user-images.githubusercontent.com/43630934/142823509-559194c1-26aa-42da-a9ca-893d44e0d443.png)

**Comment by xdlumia** [comment]
不切换清晰度时候能用吗

发自我的iPhone

**Comment by Runle1** [comment]
已解决
