### ISSUE TITLE
请问是否可以支持flv？

### ISSUE THREAD

**Issue by Smecta** [xdlumia/vue3-video-play#38]

**Comment by xdlumia** [comment]
不支持flv




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xdlumia/vue3-video-play"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 晚上6:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xdlumia/vue3-video-play] 请问是否可以支持flv？ (Issue #38)

**Comment by xdlumia** [comment]
暂时不支持呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月12日(星期天) 晚上8:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xdlumia/vue3-video-play] 请问是否可以支持flv？ (Issue #38)





 
Closed #38.
