### ISSUE TITLE
poster 设置不生效

### ISSUE THREAD

**Issue by gitrl** [xdlumia/vue3-video-play#5]
动态传的poster没生效，一直都默认的那个。。。求解

**Comment by xdlumia** [comment]
> 动态传的poster没生效，一直都默认的那个。。。求解

这是一个bug， 最晚 明天晚上我会修复这个bug，请关注最新版本

**Comment by gitrl** [comment]
好的，谢谢。默认页面中间能展示播放按钮吗？类似暂停时 的效果。

**Comment by xdlumia** [comment]
> 好的，谢谢。默认页面中间能展示播放按钮吗？我的意思是一开始的时候，点击中间播放按钮开始播放，类似暂停时 的效果。

你目前使用的是哪个版本呢？ 2.5之后的版本暂停之后 中间是有播放按钮的

**Comment by gitrl** [comment]
暂停的时候是有的，我是说，一开始进来还没播的时候也希望中间有播放按钮

**Comment by gitrl** [comment]
![image](https://user-images.githubusercontent.com/32767952/131481179-fc0b52ad-1e17-48a2-876e-15995b20cb0c.png)
这个时候

**Comment by gitrl** [comment]
还有个问题，就是 右下角的控制按钮可以动态配置吗？有些不需要，哈哈哈。

**Comment by xdlumia** [comment]
> 还有个问题，就是 右下角的控制按钮可以动态配置吗？有些不需要，哈哈哈。

1.3.1-beta.1  版本解决了这些问题 你可以更新一下看看 http://vue3-video-play.dreamwq.com/guide/changelog.html

**Comment by gitrl** [comment]
好的，看到了，谢谢啦。

**Comment by xdlumia** [comment]
> 好的，看到了，谢谢啦。

那我关闭了

**Comment by gitrl** [comment]
好嘞

**Comment by gitrl** [comment]
想问问是否只传flv 等其他格式的 直播呢？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xdlumia/vue3-video-play"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xdlumia/vue3-video-play] poster 设置不生效 (#5)





  
还有个问题，就是 右下角的控制按钮可以动态配置吗？有些不需要，哈哈哈。
  
1.3.1-beta.1  版本解决了这些问题 你可以更新一下看看 http://vue3-video-play.dreamwq.com/guide/changelog.html
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
