### ISSUE TITLE
右键

### ISSUE THREAD

**Issue by time202051** [xdlumia/vue3-video-play#75]
右键显示视频色彩调整，快捷键说明等无点击效果，且无法取消。如果生效或如何禁用调右键

**Comment by aswdw** [comment]
有答案了嘛 老哥

**Comment by time202051** [comment]
> 有答案了嘛 老哥

  let chArr: any = document.body.getElementsByClassName("d-player-contextmenu");
  for (let i = 0; i < chArr.length; i++) {
    //删除元素 元素.parentNode.removeChild(元素);
    if (chArr[i] != null) chArr[i]?.parentNode.removeChild(chArr[i]);
  }
